version: "2"
services:
  web:
    restart: always
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./web:/app"
      - "/app/node_modules"
    stdin_open: true
  worker:
    restart: always
    image: worker
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker:/go/src/github.com/s3f4/go-load/worker
