version: "3.8"
services:
  web:
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    image: worker
    volumes:
      - ./worker:/go/src/github.com/s3f4/go-load/worker
