---
- hosts: all
  become: true
  connection: ssh
  gather_facts: yes
  become_method: sudo
  tasks:
    - name: Add registry line
      lineinfile:
        path: /etc/hosts
        line: "{{ addr }} registry.dev"
