---
- hosts: master
  become: true
  connection: ssh
  gather_facts: yes
  become_method: sudo
  tasks:
    - name: Init a new swarm with default parameters
      shell: >
        docker swarm init --advertise-addr={{ addr }}:2377
    - name: Build images
      shell: >
        sh /root/app/build.sh
    - name: Deploy stack
      shell: >
        docker stack deploy -c /root/app/swarm-prod.yml go-load
    # - name: Add nodes
    #   community.general.docker_swarm:
    #     state: join
    #     advertise_addr: "{{ masterIp }}"
    #     join_token: "{{ token }}"
    #     remote_addrs: ["{{ dataIp }}:2377"]
    # - name: Deploy stack from a compose file
    #   community.general.docker_stack:
    #     state: present
    #     name: go-load
    #     compose:
    #       - /app/swarm-prod.yml
