---
- hosts: data
  become: true
  connection: ssh
  gather_facts: yes
  become_method: sudo
  tasks:
    - name: data is joining to swarm
      shell: >
        docker swarm join
        --token {{ token }}
        {{ addr }}:2377
    # - name: Add nodes
    #   community.general.docker_swarm:
    #     state: join
    #     advertise_addr: "{{ masterIp }}"
    #     join_token: "{{ token }}"
    #     remote_addrs: ["{{ dataIp }}:2377"]
    # - name: Deploy stack from a compose file
    #   community.general.docker_stack:
    #     state: present
    #     name: go-load
    #     compose:
    #       - /app/swarm-prod.yml
