FROM golang:latest

WORKDIR /go/src/github.com/s3f4/go-load/event-handler

COPY . .

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]

ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -o event-handler" -command="./event-handler"