FROM golang:1.15.2-alpine3.12

RUN apk --update add openssh-client

WORKDIR /go/src/github.com/s3f4/go-load/apigateway/cmd
COPY ./cmd/install-terraform.sh .
COPY ./cmd/install-ansible.sh .

RUN ./install-terraform.sh
RUN ./install-ansible.sh

WORKDIR /go/src/github.com/s3f4/go-load/apigateway
COPY . .

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]
EXPOSE 3001

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

CMD /wait && CompileDaemon -directory=cmd/. -log-prefix=false -build="go build -o apigateway" -command="./cmd/apigateway"