FROM golang:latest

WORKDIR /go/src/github.com/s3f4/go-load/apigateway

COPY . .

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]
EXPOSE 3001
ENTRYPOINT CompileDaemon -directory=cmd/. -log-prefix=false -build="go build -o apigateway" -command="./cmd/apigateway"