---
- hosts: workers
  become: true
  connection: ssh
  gather_facts: yes
  become_method: sudo
  tasks:
    - name: Creates directory
      file:
        path: /etc/docker/certs.d/registry.dev:5000/
        state: directory
    - copy:
        src: /app/registry.crt
        dest: /etc/docker/certs.d/registry.dev:5000/ca.crt
        owner: root
        group: root
        mode: 0644
