---
- hosts: master
  become: true
  connection: ssh
  gather_facts: yes
  become_method: sudo
  tasks:
    - name: Add label to worker node
      shell: >
        docker node update --label-add role=worker {{ node_id }}
