---
- hosts: workers
  become: true
  connection: ssh
  gather_facts: yes
  become_method: sudo
  tasks:
    - name: data is joining to swarm
      shell: >
        docker swarm join
        --token {{ token }}
        {{ addr }}:2377
