FROM golang:latest

WORKDIR /go/src/github.com/s3f4/go-load/eventhandler

COPY . .

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

CMD /wait && CompileDaemon -directory=cmd/. -log-prefix=false -build="go build -o eventhandler" -command="./cmd/eventhandler"