// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	models "github.com/s3f4/go-load/apigateway/models"
	mock "github.com/stretchr/testify/mock"
)

// authHandlerInterface is an autogenerated mock type for the authHandlerInterface type
type authHandlerInterface struct {
	mock.Mock
}

// CurrentUser provides a mock function with given fields: w, r
func (_m *authHandlerInterface) CurrentUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RefreshToken provides a mock function with given fields: w, r
func (_m *authHandlerInterface) RefreshToken(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ResponseWithCookie provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *authHandlerInterface) ResponseWithCookie(_a0 http.ResponseWriter, _a1 *http.Request, _a2 *models.User, _a3 *models.AccessToken, _a4 *models.RefreshToken) {
	_m.Called(_a0, _a1, _a2, _a3, _a4)
}

// Signin provides a mock function with given fields: w, r
func (_m *authHandlerInterface) Signin(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Signout provides a mock function with given fields: w, r
func (_m *authHandlerInterface) Signout(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Signup provides a mock function with given fields: w, r
func (_m *authHandlerInterface) Signup(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
