// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/s3f4/go-load/apigateway/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// CreateAuthCache provides a mock function with given fields: at, rt
func (_m *AuthService) CreateAuthCache(at *models.AccessToken, rt *models.RefreshToken) error {
	ret := _m.Called(at, rt)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.AccessToken, *models.RefreshToken) error); ok {
		r0 = rf(at, rt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAuthCache provides a mock function with given fields: UUID
func (_m *AuthService) DeleteAuthCache(UUID string) error {
	ret := _m.Called(UUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(UUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAuthCache provides a mock function with given fields: UUID
func (_m *AuthService) GetAuthCache(UUID string) (string, error) {
	ret := _m.Called(UUID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(UUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(UUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
