// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// BaseRepository is an autogenerated mock type for the BaseRepository type
type BaseRepository struct {
	mock.Mock
}

// GetDB provides a mock function with given fields:
func (_m *BaseRepository) GetDB() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Migrate provides a mock function with given fields:
func (_m *BaseRepository) Migrate() {
	_m.Called()
}
