// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// handlerFunc is an autogenerated mock type for the handlerFunc type
type handlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: w, r
func (_m *handlerFunc) Execute(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
