// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// InstanceHandler is an autogenerated mock type for the InstanceHandler type
type InstanceHandler struct {
	mock.Mock
}

// Destroy provides a mock function with given fields: w, r
func (_m *InstanceHandler) Destroy(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetInstanceInfo provides a mock function with given fields: w, r
func (_m *InstanceHandler) GetInstanceInfo(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetInstanceInfoFromTerraform provides a mock function with given fields: w, r
func (_m *InstanceHandler) GetInstanceInfoFromTerraform(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ShowAccount provides a mock function with given fields: w, r
func (_m *InstanceHandler) ShowAccount(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ShowRegions provides a mock function with given fields: w, r
func (_m *InstanceHandler) ShowRegions(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ShowSwarmNodes provides a mock function with given fields: w, r
func (_m *InstanceHandler) ShowSwarmNodes(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// SpinUp provides a mock function with given fields: w, r
func (_m *InstanceHandler) SpinUp(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
