// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/s3f4/go-load/apigateway/models"
	mock "github.com/stretchr/testify/mock"
)

// InstanceRepository is an autogenerated mock type for the InstanceRepository type
type InstanceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *InstanceRepository) Create(_a0 *models.InstanceConfig) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.InstanceConfig) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0
func (_m *InstanceRepository) Delete(_a0 *models.InstanceConfig) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.InstanceConfig) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields:
func (_m *InstanceRepository) Get() (*models.InstanceConfig, error) {
	ret := _m.Called()

	var r0 *models.InstanceConfig
	if rf, ok := ret.Get(0).(func() *models.InstanceConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InstanceConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFromTerraform provides a mock function with given fields:
func (_m *InstanceRepository) GetFromTerraform() ([]models.InstanceTerraform, error) {
	ret := _m.Called()

	var r0 []models.InstanceTerraform
	if rf, ok := ret.Get(0).(func() []models.InstanceTerraform); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.InstanceTerraform)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
