// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// instanceHandlerInterface is an autogenerated mock type for the instanceHandlerInterface type
type instanceHandlerInterface struct {
	mock.Mock
}

// Destroy provides a mock function with given fields: w, r
func (_m *instanceHandlerInterface) Destroy(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetInstanceInfo provides a mock function with given fields: w, r
func (_m *instanceHandlerInterface) GetInstanceInfo(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetInstanceInfoFromTerraform provides a mock function with given fields: w, r
func (_m *instanceHandlerInterface) GetInstanceInfoFromTerraform(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ShowAccount provides a mock function with given fields: w, r
func (_m *instanceHandlerInterface) ShowAccount(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ShowRegions provides a mock function with given fields: w, r
func (_m *instanceHandlerInterface) ShowRegions(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ShowSwarmNodes provides a mock function with given fields: w, r
func (_m *instanceHandlerInterface) ShowSwarmNodes(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// SpinUp provides a mock function with given fields: w, r
func (_m *instanceHandlerInterface) SpinUp(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
