// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	amqp "github.com/streadway/amqp"
	mock "github.com/stretchr/testify/mock"
)

// processFunc is an autogenerated mock type for the processFunc type
type processFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: d, exit
func (_m *processFunc) Execute(d *amqp.Delivery, exit chan<- struct{}) error {
	ret := _m.Called(d, exit)

	var r0 error
	if rf, ok := ret.Get(0).(func(*amqp.Delivery, chan<- struct{}) error); ok {
		r0 = rf(d, exit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
