// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// RunTestHandler is an autogenerated mock type for the RunTestHandler type
type RunTestHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *RunTestHandler) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Delete provides a mock function with given fields: w, r
func (_m *RunTestHandler) Delete(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Get provides a mock function with given fields: w, r
func (_m *RunTestHandler) Get(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// List provides a mock function with given fields: w, r
func (_m *RunTestHandler) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ListByTestID provides a mock function with given fields: w, r
func (_m *RunTestHandler) ListByTestID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
