// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// runTestHandlerInterface is an autogenerated mock type for the runTestHandlerInterface type
type runTestHandlerInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *runTestHandlerInterface) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Delete provides a mock function with given fields: w, r
func (_m *runTestHandlerInterface) Delete(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Get provides a mock function with given fields: w, r
func (_m *runTestHandlerInterface) Get(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// List provides a mock function with given fields: w, r
func (_m *runTestHandlerInterface) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ListByTestID provides a mock function with given fields: w, r
func (_m *runTestHandlerInterface) ListByTestID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
