// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// TestHandler is an autogenerated mock type for the TestHandler type
type TestHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *TestHandler) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Delete provides a mock function with given fields: w, r
func (_m *TestHandler) Delete(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Get provides a mock function with given fields: w, r
func (_m *TestHandler) Get(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// List provides a mock function with given fields: w, r
func (_m *TestHandler) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ListByTestGroupID provides a mock function with given fields: w, r
func (_m *TestHandler) ListByTestGroupID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Start provides a mock function with given fields: w, r
func (_m *TestHandler) Start(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Update provides a mock function with given fields: w, r
func (_m *TestHandler) Update(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
