// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/s3f4/go-load/apigateway/models"
	mock "github.com/stretchr/testify/mock"
)

// TestService is an autogenerated mock type for the TestService type
type TestService struct {
	mock.Mock
}

// Start provides a mock function with given fields: test
func (_m *TestService) Start(test *models.Test) (*models.RunTest, error) {
	ret := _m.Called(test)

	var r0 *models.RunTest
	if rf, ok := ret.Get(0).(func(*models.Test) *models.RunTest); ok {
		r0 = rf(test)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RunTest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Test) error); ok {
		r1 = rf(test)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
