// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// TestGroupHandler is an autogenerated mock type for the TestGroupHandler type
type TestGroupHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *TestGroupHandler) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Delete provides a mock function with given fields: w, r
func (_m *TestGroupHandler) Delete(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Get provides a mock function with given fields: w, r
func (_m *TestGroupHandler) Get(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// List provides a mock function with given fields: w, r
func (_m *TestGroupHandler) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Update provides a mock function with given fields: w, r
func (_m *TestGroupHandler) Update(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
