// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// testHandlerInterface is an autogenerated mock type for the testHandlerInterface type
type testHandlerInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *testHandlerInterface) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Delete provides a mock function with given fields: w, r
func (_m *testHandlerInterface) Delete(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Get provides a mock function with given fields: w, r
func (_m *testHandlerInterface) Get(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// List provides a mock function with given fields: w, r
func (_m *testHandlerInterface) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ListByTestGroupID provides a mock function with given fields: w, r
func (_m *testHandlerInterface) ListByTestGroupID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Start provides a mock function with given fields: w, r
func (_m *testHandlerInterface) Start(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Update provides a mock function with given fields: w, r
func (_m *testHandlerInterface) Update(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
