// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// workerHandlerInterface is an autogenerated mock type for the workerHandlerInterface type
type workerHandlerInterface struct {
	mock.Mock
}

// List provides a mock function with given fields: w, r
func (_m *workerHandlerInterface) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Stop provides a mock function with given fields: w, r
func (_m *workerHandlerInterface) Stop(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
