FROM golang:1.15.2-alpine3.12
ENV CGO_ENABLED 0

WORKDIR /app/
COPY . .

RUN go build -gcflags "all=-N -l" -o worker ./cmd 
RUN go get github.com/go-delve/delve/cmd/dlv

EXPOSE  2347
CMD ["dlv", "--listen=:2347", "--headless=true",  "--api-version=2","--log=true","--log-output=debugger,debuglineerr,gdbwire,lldbout,rpc", "--accept-multiclient", "debug", "/app/cmd"]

