FROM golang:alpine as builder
RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates
RUN mkdir /build
COPY . /build/
WORKDIR /build

RUN go mod download
RUN go mod verify
RUN GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -o worker

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /build/worker /app/
WORKDIR /app/
CMD [ "./worker" ]
