FROM golang:alpine
WORKDIR /go/src/github.com/s3f4/go-load/worker
COPY . .
RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]
ENTRYPOINT CompileDaemon -directory=cmd/.  -build="go build -o worker" -command="./cmd/worker"
